### ISSUE TITLE
Fasttext or fasttextmirror?

### ISSUE THREAD

**Issue by mar-muel** [crowdbreaks/text-classification#10]
In requiremements `fasttextmirror` is required, however, the import statements require `fasttext`

**Comment by francoispichard** [comment]
I will remove `fasttextmirror` from requirements.txt and replace it with `fasttext`. Note that both packages should not be present at the same time (see [this conversation on Google Groups](https://groups.google.com/g/annif-users/c/cGEL2-h7rr4/m/Jd_g7XCHBgAJ) and [this GitHub discussion](https://github.com/NatLibFi/Annif/pull/386#issue-564057251)).

Besides that requirements.txt should be updated so as to include spaCy v3.2 and the [associated version of `en_core_web_sm`](https://github.com/explosion/spacy-models/releases/tag/en_core_web_sm-3.2.0).
